version: 1
general:
  checkForUpdates: true
  updateOnBlockDamage: true
  bypassNotification: true
  initialRadius: 1
  updateRadius: 2
  proximityHiderRunnerSize: 4
cache:
  enabled: true
  baseDirectory: orebfuscator_cache
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000
  maximumSize: 8192
  expireAfterAccess: 30000
  maximumTaskQueueSize: 32768
  protocolLibThreads: -1
world:
- enabled: true
  worlds:
  - world
  hiddenBlocks:
  - minecraft:chest
  - minecraft:ender_chest
  - minecraft:trapped_chest
  - minecraft:spawner
  - minecraft:emerald_ore
  - minecraft:diamond_ore
  - minecraft:gold_ore
  - minecraft:iron_ore
  - minecraft:coal_ore
  - minecraft:lapis_ore
  - minecraft:redstone_ore
  - minecraft:stone
  - minecraft:clay
  - minecraft:shulker_box
  - minecraft:white_shulker_box
  - minecraft:orange_shulker_box
  - minecraft:magenta_shulker_box
  - minecraft:light_blue_shulker_box
  - minecraft:yellow_shulker_box
  - minecraft:lime_shulker_box
  - minecraft:pink_shulker_box
  - minecraft:gray_shulker_box
  - minecraft:light_gray_shulker_box
  - minecraft:cyan_shulker_box
  - minecraft:purple_shulker_box
  - minecraft:blue_shulker_box
  - minecraft:brown_shulker_box
  - minecraft:green_shulker_box
  - minecraft:red_shulker_box
  - minecraft:black_shulker_box
  randomBlocks:
    minecraft:cave_air: 45
    minecraft:clay: 1
    minecraft:coal_ore: 1
    minecraft:cobblestone: 1
    minecraft:diamond_ore: 25
    minecraft:emerald_ore: 10
    minecraft:gold_ore: 5
    minecraft:iron_ore: 5
    minecraft:lapis_ore: 1
    minecraft:mossy_cobblestone: 1
    minecraft:obsidian: 1
    minecraft:redstone_ore: 1
    minecraft:stone: 1
    minecraft:tnt: 1
- enabled: true
  worlds:
  - world_nether
  hiddenBlocks:
  - minecraft:chest
  - minecraft:ender_chest
  - minecraft:trapped_chest
  - minecraft:spawner
  - minecraft:netherrack
  - minecraft:nether_quartz_ore
  - minecraft:shulker_box
  - minecraft:white_shulker_box
  - minecraft:orange_shulker_box
  - minecraft:magenta_shulker_box
  - minecraft:light_blue_shulker_box
  - minecraft:yellow_shulker_box
  - minecraft:lime_shulker_box
  - minecraft:pink_shulker_box
  - minecraft:gray_shulker_box
  - minecraft:light_gray_shulker_box
  - minecraft:cyan_shulker_box
  - minecraft:purple_shulker_box
  - minecraft:blue_shulker_box
  - minecraft:brown_shulker_box
  - minecraft:green_shulker_box
  - minecraft:red_shulker_box
  - minecraft:black_shulker_box
  - minecraft:ancient_debris
  - minecraft:nether_gold_ore
  - minecraft:basalt
  - minecraft:soul_sand
  - minecraft:soul_soil
  randomBlocks:
    minecraft:netherrack: 4
    minecraft:nether_quartz_ore: 1
    minecraft:nether_gold_ore: 1
    minecraft:ancient_debris: 1
- enabled: true
  worlds:
  - world_the_end
  hiddenBlocks:
  - minecraft:chest
  - minecraft:ender_chest
  - minecraft:trapped_chest
  - minecraft:spawner
  - minecraft:shulker_box
  - minecraft:white_shulker_box
  - minecraft:orange_shulker_box
  - minecraft:magenta_shulker_box
  - minecraft:light_blue_shulker_box
  - minecraft:yellow_shulker_box
  - minecraft:lime_shulker_box
  - minecraft:pink_shulker_box
  - minecraft:gray_shulker_box
  - minecraft:light_gray_shulker_box
  - minecraft:cyan_shulker_box
  - minecraft:purple_shulker_box
  - minecraft:blue_shulker_box
  - minecraft:brown_shulker_box
  - minecraft:green_shulker_box
  - minecraft:red_shulker_box
  - minecraft:black_shulker_box
  randomBlocks:
    minecraft:end_stone: 1
    minecraft:end_stone_bricks: 1
    minecraft:bedrock: 1
    minecraft:obsidian: 1
    minecraft:purpur_block: 1
proximity:
- enabled: true
  worlds:
  - world
  distance: 16
  useFastGazeCheck: false
  defaults:
    y: 0
    above: true
    useBlockBelow: true
  hiddenBlocks:
    minecraft:diamond_ore: {}
    minecraft:emerald_ore: {}
    minecraft:chest: {}
    minecraft:ender_chest: {}
    minecraft:trapped_chest: {}
    minecraft:anvil: {}
    minecraft:crafting_table: {}
    minecraft:dispenser: {}
    minecraft:enchanting_table: {}
    minecraft:furnace: {}
    minecraft:blast_furnace: {}
    minecraft:cartography_table: {}
    minecraft:fletching_table: {}
    minecraft:grindstone: {}
    minecraft:composter: {}
    minecraft:lectern: {}
    minecraft:loom: {}
    minecraft:smithing_table: {}
    minecraft:smoker: {}
    minecraft:stonecutter: {}
    minecraft:hopper: {}
    minecraft:spawner: {}
    minecraft:shulker_box: {}
    minecraft:white_shulker_box: {}
    minecraft:orange_shulker_box: {}
    minecraft:magenta_shulker_box: {}
    minecraft:light_blue_shulker_box: {}
    minecraft:yellow_shulker_box: {}
    minecraft:lime_shulker_box: {}
    minecraft:pink_shulker_box: {}
    minecraft:gray_shulker_box: {}
    minecraft:light_gray_shulker_box: {}
    minecraft:cyan_shulker_box: {}
    minecraft:purple_shulker_box: {}
    minecraft:blue_shulker_box: {}
    minecraft:brown_shulker_box: {}
    minecraft:green_shulker_box: {}
    minecraft:red_shulker_box: {}
    minecraft:black_shulker_box: {}
    minecraft:bee_nest: {}
    minecraft:beehive: {}
  randomBlocks:
    minecraft:stone: 1
- enabled: true
  worlds:
  - world_nether
  distance: 16
  useFastGazeCheck: false
  defaults:
    y: 0
    above: true
    useBlockBelow: true
  hiddenBlocks:
    minecraft:chest: {}
    minecraft:ender_chest: {}
    minecraft:trapped_chest: {}
    minecraft:anvil: {}
    minecraft:crafting_table: {}
    minecraft:dispenser: {}
    minecraft:enchanting_table: {}
    minecraft:furnace: {}
    minecraft:blast_furnace: {}
    minecraft:cartography_table: {}
    minecraft:fletching_table: {}
    minecraft:grindstone: {}
    minecraft:composter: {}
    minecraft:lectern: {}
    minecraft:loom: {}
    minecraft:smithing_table: {}
    minecraft:smoker: {}
    minecraft:stonecutter: {}
    minecraft:hopper: {}
    minecraft:spawner: {}
    minecraft:shulker_box: {}
    minecraft:white_shulker_box: {}
    minecraft:orange_shulker_box: {}
    minecraft:magenta_shulker_box: {}
    minecraft:light_blue_shulker_box: {}
    minecraft:yellow_shulker_box: {}
    minecraft:lime_shulker_box: {}
    minecraft:pink_shulker_box: {}
    minecraft:gray_shulker_box: {}
    minecraft:light_gray_shulker_box: {}
    minecraft:cyan_shulker_box: {}
    minecraft:purple_shulker_box: {}
    minecraft:blue_shulker_box: {}
    minecraft:brown_shulker_box: {}
    minecraft:green_shulker_box: {}
    minecraft:red_shulker_box: {}
    minecraft:black_shulker_box: {}
    minecraft:bee_nest: {}
    minecraft:beehive: {}
    minecraft:ancient_debris: {}
    minecraft:nether_gold_ore: {}
    minecraft:respawn_anchor: {}
  randomBlocks:
    minecraft:netherrack: 4
    minecraft:nether_quartz_ore: 1
    minecraft:nether_gold_ore: 1
    minecraft:ancient_debris: 1
- enabled: true
  worlds:
  - world_the_end
  distance: 16
  useFastGazeCheck: false
  defaults:
    y: 0
    above: true
    useBlockBelow: true
  hiddenBlocks:
    minecraft:chest: {}
    minecraft:ender_chest: {}
    minecraft:trapped_chest: {}
    minecraft:anvil: {}
    minecraft:crafting_table: {}
    minecraft:dispenser: {}
    minecraft:enchanting_table: {}
    minecraft:furnace: {}
    minecraft:blast_furnace: {}
    minecraft:cartography_table: {}
    minecraft:fletching_table: {}
    minecraft:grindstone: {}
    minecraft:composter: {}
    minecraft:lectern: {}
    minecraft:loom: {}
    minecraft:smithing_table: {}
    minecraft:smoker: {}
    minecraft:stonecutter: {}
    minecraft:hopper: {}
    minecraft:spawner: {}
    minecraft:shulker_box: {}
    minecraft:white_shulker_box: {}
    minecraft:orange_shulker_box: {}
    minecraft:magenta_shulker_box: {}
    minecraft:light_blue_shulker_box: {}
    minecraft:yellow_shulker_box: {}
    minecraft:lime_shulker_box: {}
    minecraft:pink_shulker_box: {}
    minecraft:gray_shulker_box: {}
    minecraft:light_gray_shulker_box: {}
    minecraft:cyan_shulker_box: {}
    minecraft:purple_shulker_box: {}
    minecraft:blue_shulker_box: {}
    minecraft:brown_shulker_box: {}
    minecraft:green_shulker_box: {}
    minecraft:red_shulker_box: {}
    minecraft:black_shulker_box: {}
    minecraft:bee_nest: {}
    minecraft:beehive: {}
  randomBlocks:
    minecraft:end_stone: 1
